name: CI/CD

on:
  push:
    branches: [ main ]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with: node-version: '20'
      - run: npm ci
      - run: npm test

  build-and-push-backend:
    needs: test-backend
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build & push backend image
        run: |
          docker buildx build \
            --platform linux/amd64 \
            -t d1204/recipebook-backend:latest \
            --push .
  deploy:
    needs: build-and-push-backend
    runs-on: ubuntu-latest
    steps:
      - name: SSH & deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull d1204/recipebook-backend:latest
            docker stop recipebook-backend-container || true
            docker rm   recipebook-backend-container || true
            docker run -d --restart unless-stopped \
              -p 127.0.0.1:3000:3000 \
              --name recipebook-backend-container \
              d1204/recipebook-backend:latest
